"""Decide how to attach aitlc's runner to a behave invocation.

behave grew the custom-runner option gradually and named it differently
along the way — `--runner-class` in 1.2.7 development builds, `--runner` /
`-r` in 1.3+, and neither in the widely deployed 1.2.6. A tool that
hardcodes one flag works on one slice of installs and fails confusingly on
the rest, so the flag is detected rather than assumed.

When no flag exists, instrumentation still works: a generated
`sitecustomize.py` is placed on PYTHONPATH, which Python imports
automatically at interpreter startup, and it patches
`behave.runner.ModelRunner.run_hook` in place. That path is strictly a
fallback — the supported option is preferred wherever it exists, because
monkey-patching is more fragile than an extension point the framework
documents.

Either way the target project is untouched.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

RUNNER_MODULE = "aitlc.runtime.runner"
RUNNER_CLASS = "AitlcRunner"

# The two flags also disagree on how the class is spelled, which is easy to
# miss because both "look right". behave 1.2.7's --runner-class parses with
# `path.rsplit(".", 1)`, so it needs a fully dotted path; 1.3+'s --runner
# takes a scoped "module:Class". Passing the wrong shape fails inside
# behave's own argument parser with "No module named ...", which reads like
# aitlc is not installed rather than like a formatting mismatch.
RUNNER_PATH_BY_FLAG = {
    "--runner-class": f"{RUNNER_MODULE}.{RUNNER_CLASS}",
    "--runner": f"{RUNNER_MODULE}:{RUNNER_CLASS}",
}

# Kept for callers that just want "the scoped form".
RUNNER_PATH = f"{RUNNER_MODULE}:{RUNNER_CLASS}"

# The generated fallback. Kept as a template rather than a shipped file so
# it can be written into a throwaway directory per run, and so it never
# shadows a real sitecustomize the user already relies on (see plan()).
_SITECUSTOMIZE = '''\
"""Generated by aitlc. Instruments behave without modifying the project."""
import os


def _install() -> None:
    if os.environ.get("AITLC_INSTRUMENT") != "1":
        return
    try:
        from behave.runner import ModelRunner
    except Exception:
        # Imported by every Python process that inherits PYTHONPATH,
        # including launchers that have no behave. Nothing to do there.
        return

    import sys

    sys.path.insert(0, {aitlc_src!r})
    try:
        from aitlc.runtime.runner import AitlcRunner
    except Exception:
        return

    original = ModelRunner.run_hook

    def patched(self, name, context, *args):
        # Reuse the exact same logic as the supported path so the two
        # mechanisms cannot drift in behaviour.
        return AitlcRunner.run_hook(self, name, context, *args)

    patched._aitlc_original = original
    ModelRunner.run_hook = patched


_install()
'''


@dataclass
class AttachPlan:
    """How to attach instrumentation to one behave invocation."""

    extra_args: list[str] = field(default_factory=list)
    env: dict[str, str] = field(default_factory=dict)
    mechanism: str = "none"
    detail: str = ""


def detect_runner_flag(behave_cmd: list[str], cwd: Path) -> tuple[str | None, str]:
    """Return (flag, reason) for the custom-runner option this behave supports.

    Asks behave itself rather than parsing a version string: a fork or a
    vendored build can support the option without matching upstream
    numbering, and `--help` is the authoritative answer for the binary
    actually being invoked.

    The reason is returned alongside because "behave has no such option"
    and "behave could not be run at all" lead to the same fallback but are
    completely different problems to debug — reporting the first when the
    second happened sends people looking at the wrong thing.
    """
    try:
        proc = subprocess.run(
            [*behave_cmd, "--help"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return None, f"could not run behave to probe its options ({exc})"

    help_text = proc.stdout + proc.stderr
    if proc.returncode != 0 or "usage" not in help_text.lower():
        snippet = help_text.strip().splitlines()[:1]
        return None, (
            "could not probe behave's options"
            + (f": {snippet[0][:120]}" if snippet else "")
        )

    for flag in ("--runner-class", "--runner"):
        if flag in help_text:
            return flag, f"behave supports {flag}"
    return None, "this behave build has no custom-runner option"


def plan(
    behave_cmd: list[str],
    cwd: Path,
    work_dir: Path,
    *,
    aitlc_src: Path,
    pause_on_failure: bool = False,
    events_path: Path | None = None,
    gate_env: dict | None = None,
) -> AttachPlan:
    """Build the arguments and environment needed to instrument a run.

    gate_env carries the single-stepping gate's variables (AITLC_GATE and its
    socket/park/progress paths). Like the pause/events vars, its presence is
    what makes the runner attach at all; unlike them it also drives the gate
    behaviour in the runner.
    """
    env: dict[str, str] = {}
    if pause_on_failure:
        env["AITLC_PAUSE_ON_FAILURE"] = "1"
    if events_path is not None:
        env["AITLC_EVENTS"] = str(events_path)
    if gate_env:
        env.update({k: str(v) for k, v in gate_env.items()})

    if not env:
        return AttachPlan(mechanism="none", detail="no instrumentation requested")

    flag, reason = detect_runner_flag(behave_cmd, cwd)
    if flag:
        # aitlc's own package must be importable from the target's
        # interpreter for behave to resolve the runner path.
        env["PYTHONPATH"] = str(aitlc_src)
        return AttachPlan(
            extra_args=[flag, RUNNER_PATH_BY_FLAG[flag]],
            env=env,
            mechanism="runner-class",
            detail=f"using behave's {flag} option",
        )

    work_dir.mkdir(parents=True, exist_ok=True)
    (work_dir / "sitecustomize.py").write_text(
        _SITECUSTOMIZE.format(aitlc_src=str(aitlc_src))
    )
    env["AITLC_INSTRUMENT"] = "1"
    env["PYTHONPATH"] = str(work_dir)
    return AttachPlan(
        env=env,
        mechanism="sitecustomize",
        detail=(
            f"{reason}; falling back to patching ModelRunner.run_hook "
            "via a generated sitecustomize"
        ),
    )
