"""Build the PEP 723 single-file distribution.

Writes dist/aitlc_single.py (ARCHITECTURE.md §7, mode 2).

Technique: embed every real module's source (unmodified) as a
{relative_path: source} mapping, base64+zlib-compressed to keep the
generated file's size reasonable. A small bootstrap at the bottom unpacks
these into a temp directory recreating the real package layout, adds it to
sys.path, and imports the real, unmodified aitlc.cli:app — so this is
exactly the same code as the installed package, not a reimplementation or
an import-rewritten copy that could drift or subtly break.

Run: `python3 scripts/build_single_file.py`
Use the result: `uv run dist/aitlc_single.py <args>` (no install step —
uv resolves the declared dependencies on the fly), or `python3
dist/aitlc_single.py <args>` if the dependencies are already available.
"""

from __future__ import annotations

import base64
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "aitlc"
DIST = ROOT / "dist"
OUTPUT = DIST / "aitlc_single.py"

PEP723_HEADER = """# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "typer>=0.12",
#     "requests>=2.31",
#     "playwright>=1.45",
#     "tomli>=2.0; python_version < '3.11'",
#     "pyyaml>=6.0",
#     "pyte>=0.8",
# ]
# ///
"""

BOOTSTRAP_TEMPLATE = '''"""aitlc — single-file distribution. Generated by scripts/build_single_file.py.

Do not edit this file directly — edit the real package under src/aitlc/
and regenerate. Run with `uv run aitlc_single.py <args>` (no install step)
or `python3 aitlc_single.py <args>` if dependencies are already installed.
"""

{pep723_header}
import base64
import sys
import tempfile
import zlib
from pathlib import Path

_MODULES = {modules_literal}


def _unpack_and_run() -> None:
    tmpdir = Path(tempfile.mkdtemp(prefix="aitlc_single_"))
    pkg_dir = tmpdir / "aitlc"
    pkg_dir.mkdir()
    for rel_path, compressed_b64 in _MODULES.items():
        source = zlib.decompress(base64.b64decode(compressed_b64)).decode("utf-8")
        target = pkg_dir / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source)

    sys.path.insert(0, str(tmpdir))
    from aitlc.cli import app

    app()


if __name__ == "__main__":
    _unpack_and_run()
'''


def build() -> None:
    """Write the single-file build to dist/."""
    modules: dict[str, str] = {}
    for path in sorted(SRC.rglob("*.py")):
        rel = path.relative_to(SRC)
        source = path.read_text()
        compressed = zlib.compress(source.encode("utf-8"), level=9)
        modules[str(rel)] = base64.b64encode(compressed).decode("ascii")

    modules_literal = repr(modules)

    output_text = BOOTSTRAP_TEMPLATE.format(
        pep723_header=PEP723_HEADER,
        modules_literal=modules_literal,
    )

    DIST.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output_text)
    print(
        f"Wrote {OUTPUT} ({len(output_text):,} bytes, {len(modules)} modules bundled)"
    )


if __name__ == "__main__":
    build()
